### PR TITLE
Packaging version 2

### PR DESCRIPTION
**Pull request by Thovi98**
## Problem

- New packaging format for Yunohost available

(potentially) fixes https://github.com/YunoHost-Apps/photoprism_ynh/issues/35

## Solution

- Begin the migration to it

Not ready yet.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Thovi98** [comment]
!testme

**Comment by Thovi98** [comment]
!testme

**Comment by Thovi98** [comment]
!testme

**Comment by Thovi98** [comment]
!testme

**Comment by Thovi98** [comment]
@Limezy ready for review 🙈🎉

**Comment by Limezy** [comment]
Wow I'm impressed !

**Comment by Thovi98** [comment]
!testme

**Pull request merged**
