### PR TITLE
Update to 220901

### PR DESCRIPTION
**Pull request by Limezy**

### CODE REVIEW

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
@Thovi98 do you know how to do a basic update like that one, when upstream makes a release ?
Basically it's as simple as : 
* Sync master branch with your own repo
* Change manifest.json to update the version (here 2022.09.01~ynh1)
* Go to https://hub.docker.com/r/photoprism/photoprism/tags
* Find the container named xxxxxx-bullseye (xxxxxx being 220901 in that case)
* Click on the digest number, and copy paste to _common.sh both hash number you can find, respectively for amd64 and arm64 architectures (here, for example, the amd64 is 3381d40181ecdf62932e9530c6b81e6e0f8828a3d373d8dedf662aab96dafba4
image
* Find the container named xxxxxx-armv7 and repeat the same process to change the hash under armhf arch in _common.sh
Commit to branch, push to remote, create a pull request to testing branch
* Ping me so that I can launch the !testme CI and merge once done !

**Comment by Thovi98** [comment]
Very nice, thanks!
I think I will be able to achieve that 😄

**Comment by Limezy** [comment]
Perfect ! So next time I'll let you do it !
Merging now.

**Pull request merged**
