### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Level 0*

## Solution

- *Switch to docker*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
@Limezy I let you look and test it, to be sure photoprism works as espected

**Comment by Limezy** [comment]
Wow you did everything for me... thank you so much !

**Comment by yalh76** [comment]
your welcome, But now is the testing part ^^ and tweaking from your side ^^

maybe there is work to do around `PHOTOPRISM_VERSION="220617-bullseye"` to make it available for all architecture

**Comment by Limezy** [comment]
Installation is very fast and it works perfectly.
I'll merge, get that app to be level 7 in the catalog and then work on other architectures support.
Next step will be to wait for photoprism to implement multi-user and OIDC and interface it to Ynh userbase using Dex app !

**Pull request merged**
