### PR TITLE
Make installation compatible with arm64 and armhf architectures

### LINKED ISSUE #18: Failed to execute command: Exec format error
After successful installation service fails to start

- Hardware: Raspberry Pi 4 at home 4gb ram 6gb swap
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH | through the webadmin
- Using, or trying to install package version/branch: testing

Log: https://paste.yunohost.org/gexajeqemo

### PR DESCRIPTION
**Pull request by tituspijean**
Closes #18 

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Thovi98** [comment]
Could you please tell me where you found the `armhf` sha256? I see only the ones for amd64 and arm64 in the [Docker Hub](https://hub.docker.com/layers/photoprism/photoprism/photoprism/220730-bullseye/images/sha256-2a2fc58d5bf77642424854158a06713ce532026bd18a43e07fd71d75365cb8d3?context=explore)

And I don’t understand how the script will find Photoprism (and the right version) with only the sha256, but that’s maybe my lack of knowledge 😁

**Comment by tituspijean** [comment]
It's in another tag: https://hub.docker.com/layers/photoprism/photoprism/photoprism/220730-armv7/images/sha256-4e0b39a06e0f7ecd11aa8cbd84c739cba3417c99348f52e3433cdeaeeb5474cb?context=explore

However, I realize now that `armhf != armv7` :(

**Comment by Limezy** [comment]
Hi @tituspijean, do we have an arm64 CI ?
I don't have any arm64 architecture to test your PR on right now...

**Comment by tituspijean** [comment]
Right now, no. I had tried to make one on my RPi4. I'll try to spin it up again during today's YunoCamp session.

**Comment by Limezy** [comment]
Ok ! Hard for me to make a review of your PR, but I let you merge whenever you feel it's OK
@Thovi98 do you have a Pi or something to test on your side ?

**Review by Limezy — APPROVED** [review]
Can't test on my side, but looks good.
And also easy to add new architectures if needed !

**Comment by Thovi98** [comment]
@Thovi98 do you have a Pi or something to test on your side ?

I’ve not, sorry :(

**Comment by centralscrutinizer21** [comment]
I gave this branch a try without success
https://paste.yunohost.org/raw/orenohogix

**Comment by Limezy** [comment]
@centralscrutinizer21 : Many thanks for testing, that will be very useful.
It looks like there is still a few things to improve, I'll try to have a look.

**Comment by tituspijean** [comment]
I think I wrote a bad `case` block in `_common.sh`.

**Comment by tituspijean** [comment]
@centralscrutinizer21 you may try again. :)

**Comment by centralscrutinizer21** [comment]
@tituspijean worked like a charm!

**Comment by navanchauhan** [comment]
Why don't we simply compile the program from scratch rather than using the docker-extractor? PhotoPrism looks like a simple program written in Go https://github.com/photoprism/photoprism/blob/develop/scripts/build.sh

I am happy to contribute the relevant PR that builds on the device itself if the package maintainer wants to go in that direction. All we would need to do is include a custom helper that installs Go -> Builds a static binary -> Uninstalls Go

I did that for ListMonk a few days back ([ListMonk Repo](https://github.com/navanchauhan/listmonk_ynh))

**Comment by tituspijean** [comment]
As far as I know we moved to Docker image extraction because the compilation was taking A LOT of resources.

**Comment by Limezy** [comment]
> Why don't we simply compile the program from scratch rather than using the docker-extractor? PhotoPrism looks like a simple program written in Go https://github.com/photoprism/photoprism/blob/develop/scripts/build.sh
> 
> I am happy to contribute the relevant PR that builds on the device itself if the package maintainer wants to go in that direction. All we would need to do is include a custom helper that installs Go -> Builds a static binary -> Uninstalls Go
> 
> I did that for ListMonk a few days back ([ListMonk Repo](https://github.com/navanchauhan/listmonk_ynh))

Thanks for your proposal ! This is actually how I did package Photoprism before.
It's way harder than that in fact, because of the dozens and dozens of required dependancies, not all using the Go system.
You may have a look at past versions of the master branch if you want.

> As far as I know we moved to Docker image extraction because the compilation was taking A LOT of resources.

Yep exactly ! The CI was crashing every time.
Feel free anyway to contribute to this package, every help is warmly welcomed.
We are currently changing to have @Thovi98 as the official maintainer of the app

**Comment by Limezy** [comment]
!testme
!bullseyetestme

**Comment by Limezy** [comment]
These tests will not secure the fact that the package will work on arm64 or other architectures.
However, if the tests are running on the amd64 CI, I'll consider this PR as non regressing, hence mergeable.

**Pull request merged**
