### PR TITLE
Upgrade to 2022.11.03

### PR DESCRIPTION
**Pull request by Thovi98**
## Problem

- New version

## Solution

- Upgrade

But it seems that there are some things to do, according to [yesterday’s version](https://github.com/photoprism/photoprism/releases/tag/221102-905925b4d), I don’t know ?

@Limezy 

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
Thanks for putting that PR ! 
I believe it will not work in practice since as per what I could read in the official repo, there is a small command to run to migrate the users database. I launched the test anyway. 
Have you tried an installation on a test server ?

**Comment by Thovi98** [comment]
> there is a small command to run to migrate the users database

Yes, I’ve just searched but cannot understand how to launch this command as we are not on Docker...

And I’ve not too much time right now neither, I will try to investigate whenever it’s possible.

**Comment by Limezy** [comment]
The right command is there, but I don't know (yet) how to pass the .env variables in it...

**Comment by Limezy** [comment]
Something like `source .env && live/bin/photoprism users reset --yes` from the final path should work, but I still get the error 'invalid originals path, check configuration and permissions`

**Comment by Thovi98** [comment]
I don't understand much of it, but I don't see that you did a `source .env` ? :)

I don't see the latest Bullseye (nor Debian) tags on Dockerhub anymore, do I take the `sha` from Jammy (Ubuntu) ?

**Comment by Thovi98** [comment]
I’ve tried to manually upgrade and then do the migration command, but I come across the glibc issue:

```
/var/www/photoprism/live/bin/photoprism: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/www/photoprism/live/bin/photoprism)
/var/www/photoprism/live/bin/photoprism: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /var/www/photoprism/live/bin/photoprism)
/var/www/photoprism/live/bin/photoprism: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/www/photoprism/live/bin/photoprism)
```

I have litterally no clue.

Anyway, I wish you a merry Christmas @Limezy 🎄🕊️

**Comment by Thovi98** [comment]
Now the users database seems to work, but I’ve still the `glibc` issue.

If someone who reads this know how to upgrade docker images, see upstream https://github.com/photoprism/photoprism/discussions/3123

**Comment by Limezy** [comment]
Wow that one is still pending. Sorry I was very busy these days... all the Ynh I maintain or help to maintain are pending now !

**Comment by Limezy** [comment]
The glibc issue seems to say that there is a mismatch between the platform on which the executable was compiled and the platform on which you try to install it. Are you using a RPi ? Standard intel based server ? Let me check your PR on my test server.

**Comment by Limezy** [comment]
!testme

**Comment by Thovi98** [comment]
> The glibc issue seems to say that there is a mismatch between the platform on which the executable was compiled and the platform on which you try to install it. Are you using a RPi ? Standard intel based server ? Let me check your PR on my test server.

Oops sorry for the late answer.

I am using an intel based server. But yes, now the docker build is based on Ubuntu Jammy which has an higher glibc version.

There are several possibilities here:
- Return to an installation that build sources (but require higher ressources if I understood correctly)
- Adapt the upstream docker builds to support Bullseye again
- Find a workaround for glibc 

I don’t have enough skills for those points unfortunately :/

**Comment by BrunoSpy** [comment]
I think building from sources is the way to go as Debian will most of the time be behind Ubuntu based docker images.
There's this doc that can help : https://github.com/IndrekHaav/photoprism-debian

**Comment by Limezy** [comment]
The initial version of that package was building from sources but it was grazy long and I struggled a lot with out of memory issue. We could try going back to it but most probably it will kill any installation possibility with servers that have less than 4GB. 
Another way would be to pre-build an executable and host it on this GitHub repo, but that would require users to trust us, which is never ideal.

**Comment by Thovi98** [comment]
> We could try going back to it but most probably it will kill any installation possibility with servers that have less than 4GB.
> Another way would be to pre-build an executable and host it on this GitHub repo, but that would require users to trust us, which is never ideal.

What’s the best way to go following the Yunohost philosophy do you think @YunoHost-Apps/apps-group?

**Comment by tituspijean** [comment]
> We could try going back to it but most probably it will kill any installation possibility with servers that have less than 4GB.

Have you tried adding a swap?

> Another way would be to pre-build an executable and host it on this GitHub repo, but that would require users to trust us, which is never ideal.

We already do that for Galène or Synapse, and the users already trust us with a bunch of scripts run as root on their system, so I don't see why not :)

**Comment by Thovi98** [comment]
Thanks for your input!

> Have you tried adding a swap?

In my memories, @Limezy added a swap partition when needed...

For me either way are good to go, but I have literally no clue how to pre-build an executable 😅 
Is it far different from adapting the docker images in upstream to make Photoprism run in Bullseye again? If not, it might be better to adapt upstream like they [proposed](https://github.com/photoprism/photoprism/discussions/3123)? But doing so will only differ the issue to the next Debian upgrade?

**Comment by Salamandar** [comment]
superseeded by #40

**Pull request closed without merging**
