### PR TITLE
Update binary' env variables

### PR DESCRIPTION
**Pull request by navanchauhan**
## Problem

- Cannot convert HEIF images
- Exiftool disabled

## Solution

- Specifies Exiftool and FFMPEG as pkg_dependencies
- Adds environment variables to systemd file

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by navanchauhan** [comment]
last commit also fixes sharing issue mentioned in the last comment of #18

**Comment by navanchauhan** [comment]
!testme

**Comment by Limezy** [comment]
Hi @navanchauhan , thanks for your PR
Your intention is good but I'm not convinced about the fix.

Right now all env variables are set in the [options.yml](https://github.com/YunoHost-Apps/photoprism_ynh/blob/master/conf/options.yml) file.

As far as I understood there are two ways of passing settings to the photoprism executable : 
* A .yml format, used so far with that options.yml file
* A .env format, which for some reasons I've never been able to have working

The main problem with the .yml format is that it's not very much documented, and that the syntax is not the same.
So I feel that we should first try to switch from the .yml format to the .env format, and then integrate the few settings (PHOTOPRISM_HEIFCONVERT_BIN, PHOTOPRISM_FFMPEG_BIN, PHOTOPRISM_EXIFTOOL_BIN) as per your recommendation here !

**Comment by Limezy** [comment]
I will try to use your PR as a base for trying to switch to .env file instead of .yml.
For the permission thing, it seems not to be fully polished yet because the private test has failed.

**Comment by navanchauhan** [comment]
Oh I see. I missed the options.yml file. I would suggest moving to `EnvironmentFile` in systemd.

I am not sure why the tests are failing in private mode? Do we need to move the /s share endpoint to the is_public check?

**Comment by Limezy** [comment]
!testme
!bullseyetestme

**Comment by Limezy** [comment]
Current version seem to be working on my test server. Waiting for CI.

**Pull request merged**
