### PR TITLE
Test CI

### PR DESCRIPTION
**Pull request by Limezy**
Now that first version is usable, launch CI

### CODE REVIEW

**Comment by Limezy** [comment]
!testme

**Comment by tituspijean** [comment]
!gogogadgetotitus
(FYI I can't install it on the same server holding my CI: https://paste.yunohost.org/raw/orihotalon)

**Comment by Limezy** [comment]
Thanks @tituspijean for the speed test !
Strange, I'll try to understand what happens.
It works perfectly on my own server (fresh installed Yunohost 11.0.7)

**Comment by Limezy** [comment]
!gogogadgetotitus
(@tituspijean I take the liberty of using your CI, please tell me if you don't want me to !)

**Comment by Limezy** [comment]
I'm not sure but it looks linked to an old npm version for Buster... 
I've tried and packaged on Yunohost v11.0.7... !

**Comment by Limezy** [comment]
!bullseyetestme

**Comment by yalh76** [comment]
!testme

**Comment by tituspijean** [comment]
Yeah sorry, my server has too little ressources for building it. 😅

**Comment by Limezy** [comment]
!gogogadgetotitus

**Comment by Limezy** [comment]
!gogogadgetotitus

**Comment by Limezy** [comment]
!gogogadgetotitus

**Comment by Limezy** [comment]
!gogogadgetotitus

**Comment by Limezy** [comment]
!gogogadgetotitus

**Comment by Limezy** [comment]
!gogogadgetotitus

**Comment by Limezy** [comment]
!gogogadgetotitus

**Comment by Limezy** [comment]
!gogogadgetotitus

**Comment by jarod5001** [comment]
I think you should allocate 2G of swap besides the 2G of ram. Since the ci takes some ram to function, it will be lower on ram than a clean testing server

**Comment by Limezy** [comment]
@jarod5001 thanks for your help !
My problem right now is that no matter what amount of Swap I try to setup, it doesn't work in the CI... 
I can't figure out why, it's a real pain 🤣 
I'm a little bit frustrated given how well photoprism currently installs on my test server !

**Comment by jarod5001** [comment]
```
2301 INFO [#+..................] > The system currently has 1513 Mo of RAM...
2367 INFO [##+.................] > Adding 535 Mo to swap...
2402 WARNING lsblk: /dev/sda1: not a block device
2577 INFO [###+................] > The system now has 1513 Mo of RAM...
```
and in https://ci.pijean.ovh/ci/logs/photoprism_amd64_stable_complete.log

`514526 [37m[1mDEBUG [mFATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

If you try to add swap of 3 or 4 G regardless of the RAM ? I don't know how much disk space it requires while building it, may be in your test vps you can check free space before and during the process and try to guess how much the building requires to be able to adjust the maximum swap without running short in disk space. 
It's clearly a low memory issue.

**Comment by jarod5001** [comment]
Mmhh, I have upgraded the VM to 3G of ram and it failed.
https://paste.yunohost.org/raw/wohozohelo

```
2022-06-08 00:51:07,071: DEBUG - npm WARN npm npm does not support Node.js v10.24.0
2022-06-08 00:51:07,072: DEBUG - npm WARN npm You should probably upgrade to a newer version of node as we
2022-06-08 00:51:07,073: DEBUG - npm WARN npm can't make any promises that npm will work with this version.
```
And
```
2022-06-08 01:01:26,749: DEBUG - Installing in "/var/www/photoprism/build"...
2022-06-08 01:01:27,034: DEBUG - ERROR: Install path '/var/www/photoprism/build' already exists!
2022-06-08 01:01:27,064: DEBUG - make: *** [Makefile:86: install] Error 1 
```

**Comment by Limezy** [comment]
OK, I think I know where both problems comes from

### For the npm problem
I think it's OK because the node version is not the one provided with Buster since the package is "manually" installing node 14. I could try to "manually" install npm also instead of relying on apt package. That would be maybe cleaner, I'm not sure.

### For the `Install path already exists!`
I guess your first installation didn't work, so you need to `sudo rm -rf /var/www/photoprism` before.

Otherwise, from what I could see in the logs you have provided, everything went well including the full building stage.
`2022-06-08 01:01:26,682: DEBUG - webpack 5.72.1 compiled successfully in 136990 ms`
So it should run until the end !

This gives me some hope that in the end this package could be shipped !

**Comment by jarod5001** [comment]
But the installation was done in a clean VM. I restored the VM to a state of "right after first user creation".
I don't test in VM that has been used, there may be some things left that didn't get removed by the remove script.
I'll retry it tonight

**Comment by jarod5001** [comment]
HI, I found this
https://github.com/IndrekHaav/photoprism-debian
It may help. It recommends to use the latest versions for nodejs and go.
Good luck

**Comment by Limezy** [comment]
Wow, thanks it's a nice catch and it would have saved me a bit of time !
I'm quite happy because my method is more or less the exact same one as the one described in that tutorial.
I'll definitely try the `NODE_OPTIONS=--max_old_space_size=1024` trick, and maybe switch to the .env format instead of options.yml, I'll see if there is any substantial difference.

For your problem, I have looked at your logs and I don't see anywhere where the /var/www/photoprism/build file would be created before it's needed by the build script, that's very strange. Are you sure that your VM was clean ?

**Comment by Limezy** [comment]
!gogogadgetotitus

**Comment by Limezy** [comment]
It drives me crazy !
Now working on my Buster test VPS...
!gogogadgetotitus

**Comment by jarod5001** [comment]
Hi, I tried to add `--force` here https://github.com/jarod5001/photoprism_ynh/blob/224976b48caa4c528a9ab5dff870463e1abcaedc/scripts/install#L153
annnnnd it worked, the installation completed but I couldn't login because I typed a random password, sorry.
That's not recommended, but it may help understand why and how to fix it.
The tuto said to see https://github.com/photoprism/photoprism/blob/release/Makefile and try these steps one by one to see what's wrong. 
But, I in the last log of the ci, there is still an error `Install path '/var/www/photoprism/binaries' already exists`
Besides, why didn't you use the source releases here https://github.com/photoprism/photoprism/releases instead of git cloning ? I don't know what's better, I try to understand.
Good work, you're in the right way. I hope I could help more but I have so little time now.

**Comment by Limezy** [comment]
Many thanks for your help !

For the low ressources of the CI, the problem is now solved and I already had Titus' CI building the backend and frontend successfully. It's only a stupid problem of environment variables and scripts using the Buster basic node10 instead of the manually installed node14. 

For the npm installation bug I think I got it now, by running the different make parts separately instead of brutally running `make all install`

I'm glad it worked for you. It means I'm not so far ! 

For the git clone instead of downloading release source code it's because at some point of the building it needs to be inside a git repository. If not it would fail. I don't understand exactly why to be honest, but I could see that the tutorial you linked above is doing precisely the same thing, cloning the repo instead of downloading the source.

**Comment by Limezy** [comment]
Still some out of memory issues with Titus' CI (make error 137)
!gogogadgetotitus

**Pull request merged**
