### PR TITLE
Upgrade to latest version

### PR DESCRIPTION
**Pull request by Thovi98**
## Problem

- New version

## Solution

- Upgrade to 220730-bullseye (I hope I did the correct way)

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Limezy** [comment]
Wow great, thanks for your help.

I have packaged that app for a friend but am not using it, and don't have much time to spend on it.
Feel free to tell me if you want to become the official maintainer.

I believe the next complicated thing will be to integrate the multi-user OIDC based system, but it's not yet ready on photoprism side. When it comes I'll do it.

**Comment by Limezy** [comment]
!testme

**Comment by Limezy** [comment]
!bullseyetestme

**Comment by Limezy** [comment]
We also need to make an official announcement of that app in the forum.

**Comment by Thovi98** [comment]
> Feel free to tell me if you want to become the official maintainer.

I'm not against the idea, but I don't have the necessary skills unfortunately yet... I’m certainely open to help you merge PR’s when necessary and I’m willing to help you upgrade the package at every new version too :) 
I’m just not in the Yunohost-Apps organization, so I won’t be able to !testme.

> I believe the next complicated thing will be to integrate the multi-user OIDC based system, but it's not yet ready on photoprism side. When it comes I'll do it.

It would be so cool!

> We also need to make an official announcement of that app in the forum.

I can do it if you want!

**Comment by Thovi98** [comment]
Okay, ready to merge, beside the shitload of warnings. I don’t know  how to redirect them to the standard output. Any clue?

**Comment by Limezy** [comment]
> > Feel free to tell me if you want to become the official maintainer.
> 
> I'm not against the idea, but I don't have the necessary skills unfortunately yet... I’m certainely open to help you merge PR’s when necessary and I’m willing to help you upgrade the package at every new version too :) I’m just not in the Yunohost-Apps organization, so I won’t be able to !testme.
> 

Let me put your name inside that PR, you deserve it.
No problem, I'll stay here to help in any case.

> > We also need to make an official announcement of that app in the forum.
> 
> I can do it if you want!

With pleasure !

**Comment by Limezy** [comment]
> Okay, ready to merge, beside the shitload of warnings. I don’t know how to redirect them to the standard output. Any clue?

Let me try to solve this.

**Comment by Limezy** [comment]
!testme
!bullseyetestme

**Comment by Thovi98** [comment]
Okay I think it’s good now ! :D 
@Limezy, I don’t have any rights in the Yunohost-Apps organization so I cannot !testme nor merge.

**Comment by Limezy** [comment]
!testme
!bullseyetestme

**Comment by Thovi98** [comment]
Ping @Limezy 😇

**Comment by Limezy** [comment]
Hi @Thovi98 
I would like to merge, but do you know why there are still a lot of warnings ?

**Comment by Limezy** [comment]
Solves #16

**Comment by Thovi98** [comment]
`I would like to merge, but do you know why there are still a lot of warnings ?`

I didn’t hide the warnings for `upgrade` and `restore`, I will do that now

**Comment by Limezy** [comment]
I'll merge right after these tests are passed 🚀

**Pull request merged**
